### ISSUE TITLE
Heroku

### ISSUE THREAD

**Issue by MEZBATHEKING** [BaumianerNiklas/Waddle-Bot#11]
Make a [heroku](https://heroku.com) direct deploy button in README.md so peoples can easily use it

**Comment by BaumianerNiklas** [comment]
Can you elobarate furhter on what you mean by that? I'm not necessarily looking for a hosting provider at the moment as this is just something I do for fun in my free time. If you/other people want to host the bot yourself, you're more than welcome to clone/fork this repo and host it yourself, though! :)

**Comment by BaumianerNiklas** [comment]
Closing this since there hasn't been any clarification or activity on this in 2 months.
